### ISSUE TITLE
[blackduck] Java projects seem to have an entry namespace: "unknown" id: "null". It crashes Spdx-builder

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-software/spdx-builder#66]
# Command executed
```bash
blackduck -o fact-service-github.spdx forest fact-service-github
```

# Output
```
Building tree of components An internal error occurred: java.lang.NullPointerException
java.lang.NullPointerException
	at com.philips.research.spdxbuilder.persistence.blackduck.PackageIdentifier.fromEnd(PackageIdentifier.java:135)
	at com.philips.research.spdxbuilder.persistence.blackduck.PackageIdentifier.namespace(PackageIdentifier.java:81)
	at com.philips.research.spdxbuilder.persistence.blackduck.PackageIdentifier.getPurl(PackageIdentifier.java:28)
```

# Possilble fixes

## Report and continue
Make sure spdx-builder reports this unknown package and continue.

## Report and fail
Make sure spdx-builder reports this unknown package and stop the tool.

## Try to figure out why the unknown component is in blackduck.
A lot of java applications seem to have this "unknown" package included.. maybe a misconfiguration in blackduck configuration.

**Comment by JeroenKnoops** [comment]
Is resolved in #63
